// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.emsi.tpgrpcbanque.stubs;

public interface DeleteCompteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteCompteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
